# Generated by Django 5.1.1 on 2024-09-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Image',
        ),
    ]
